# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{active_rest}
  s.version = "2.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["vihai"]
  s.date = %q{2011-06-08}
  s.description = %q{ActiveRest provides several useful actions for restful controllers}
  s.email = %q{daniele@orlandi.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "TODO.txt",
    "VERSION",
    "lib/active_rest/controller.rb",
    "lib/active_rest/controller/filters.rb",
    "lib/active_rest/controller/rest.rb",
    "lib/active_rest/controller/validations.rb",
    "lib/active_rest/model.rb",
    "lib/active_rest/routes.rb",
    "lib/active_rest/view.rb",
    "lib/tasks/active_rest_tasks.rake"
  ]
  s.homepage = %q{http://www.yggdra.it/}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{REST controller mixin}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

