source 'http://rubygems.org'

gem 'rails', '>= 3.2.0.rc1'

gem 'sqlite3-ruby', :require => 'sqlite3'

gem 'squeel'
gem 'active_rest', '>= 3.0.1', :path => '..'

# Bundle gems for certain environments:
group :test, :development do
#  gem 'webrat'
  gem 'rspec', '>= 2.0.0'
  gem 'rspec-rails', '>= 2.0.0'
  gem 'factory_girl_rails', '>= 1.1.beta1'
  gem 'nokogiri'
  gem 'vihai-assert2', :git => 'https://github.com/vihai/assert2.git'
  gem 'rspec-deep-matchers', :git => 'http://github.com/vihai/rspec-deep-matchers.git'
end
